### ISSUE TITLE
java clients of Chill-Avro, arent able to instantiate AvroSerializer as it takes Manifest

### ISSUE THREAD

**Issue by mohangadm** [twitter/chill#199]
Java Clients of Chill-Avro can not be able to register their classes with KryoRegistrator as AvroSerializer from chill is trying to force for an argument Manifest, which a java client can not be able to create.

Provide some kind of companion object to allow java clients to register with Kryo using twitter-chill's AvroSerializer.

**Comment by pritamm** [comment]
@MansurAshraf Can you please let me know which version has the fix to use ClassManifest  instead of Manifest in the AvroSerializer? I downloaded 0.5.0 version of chill-avro from maven, is there any new version available with this fix?

**Comment by MansurAshraf** [comment]
@pritamm http://mvnrepository.com/artifact/com.twitter/chill-avro_2.11/0.9.1
