### ISSUE TITLE
Chill should Java 8

### ISSUE THREAD

**Issue by Pyrolistical** [twitter/chill#223]
chill depends on kyro 2.2.1 which only supports Java 7

The next kyro release will support Java 8, but it will be version 3.0.0+ which will require work.  reflectasm recently released a new version that supports Java 8, which kyro has already consumed.  They promise to release a new version of kyro as soon as possible.

This is blocking Spark from supporting Java 8.  See https://issues.apache.org/jira/browse/SPARK-6152

**Comment by ianoc** [comment]
So this is a no-op for now on chill since the upstream doesn't have support?

**Comment by magro** [comment]
kryo 3.0.1 was just released: https://github.com/EsotericSoftware/kryo/blob/master/CHANGES.md#2240---300-2014-0-04

Please note that in 3.0.0 the groupId changed to "com.esotericsoftware", the shaded jar is now available under artifactId "kryo-shaded".

**Comment by ianoc** [comment]
awesome @magro , Not sure when exactly i'll get to trying to incorporate it quite yet, @Pyrolistical you should be able to take a stab at this now if you've the time. Would love the PR

**Comment by Pyrolistical** [comment]
@ianoc its not a blocker for me, but this is something both `chill` and `spark` will want to do now as `scala` will require Java 8 next release.

**Comment by ianoc** [comment]
It will only require it come 2.12, which is just getting to its RC cycle now, not close to release. So not much rush for it on our end anyway.

**Comment by hepin1989** [comment]
I will take this one,it's a blocker for me.

**Comment by figpope** [comment]
#230 Should take care of this, if Kryo is the only blocker to moving to 1.8.

**Comment by ianoc** [comment]
0.8.0 has been released using 3.x kryo. Tests pass for java's 6 through 8 so should be good on this one.
