### ISSUE TITLE
Deserialization Exception in twitter/chill with Play2 and Scala 2.11.1

### ISSUE THREAD

**Issue by Ahsentaqi** [twitter/chill#239]
i am using Scala 2.11.1 and Hcast 3.5 and twitter-chill for serialization

i have a class User and serializer UserSerializer both on Server(Sbt project) and client side (Play2 project)

i am storing User object in hcast , my serializer is working fine on server but the read method of the same serializer gives me exception

here is my serializer

 // takes the bytes and converts into User Object  (Deserializer)
   @throws(classOf[IOException])
  override def read(in : ObjectDataInput) : User =  {

     log.info("***********  Deserializer from Client called  ")
      val bytes = ByteArrayConverter.getByteArray(in).toByteArray();
      log.info("Bytes size: "+bytes.length)
      val tryDecode: scala.util.Try[Object] = KryoInjection.invert(bytes)

     tryDecode match {
       case Success(obj) => log.info("  ------ Success case executed ")
                           obj.asInstanceOf[User]
       case Failure(e) => log.info("------ Failure case executed ")
       log.error("deserializer from Client : {}" ,e.printStackTrace())
       null
     }

}

the problem is at this line

     at UserSerializer.read(UserSerializer.scala:44)

which is this line from the above method

      val tryDecode: scala.util.Try[Object] = KryoInjection.invert(bytes)

i dont know whats the problem because same code works fine on hcast server but gives problem on client side

here are the complete stack traces from client side (Play2)

     17:24:48.822 276580 [play-akka.actor.default-dispatcher-7] UserSerializer INFO - ***********       Deserializer from Client called 
17:24:48.839 276597 [play-akka.actor.default-dispatcher-7] ByteArrayConverter$ INFO - ---- object to byte array converter 
17:24:48.841 276599 [play-akka.actor.default-dispatcher-7] ByteArrayConverter$ INFO - ---- conversion done now returning the byte array 
7:24:48.841 276599 [play-akka.actor.default-dispatcher-7] UserSerializer INFO - Bytes size: 596  17:24:48.917 276675 [play-akka.actor.default-dispatcher-7] UserSerializer INFO - ------

    Failure case executed com.twitter.bijection.InversionFailure: Failed to invert: [B@1296562 at
  com.twitter.bijection.InversionFailure$$anonfun$partialFailure$1.applyOrElse(InversionFailure.scala:43) at com.twitter.bijection.InversionFailure$$anonfun$partialFailure$1.applyOrElse(InversionFailure.scala:42) at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) at scala.util.Failure.recoverWith(Try.scala:203) at com.twitter.bijection.Inversion$.attempt(Inversion.scala:30) at com.twitter.chill.KryoInjection$.invert(KryoInjection.scala:29) at UserSerializer.read(UserSerializer.scala:44) at UserSerializer.read(UserSerializer.scala:22) at com.hazelcast.nio.serialization.StreamSerializerAdapter.read(StreamSerializerAdapter.java:41) at com.hazelcast.nio.serialization.SerializationServiceImpl.toObject(SerializationServiceImpl.java:276) at com.hazelcast.client.spi.ClientProxy.toObject(ClientProxy.java:173) at com.hazelcast.client.spi.ClientProxy.invoke(ClientProxy.java:131) at com.hazelcast.client.proxy.ClientMapProxy.get(ClientMapProxy.java:200) at
play.api.mvc.ActionBuilder$$anonfun$apply$17.apply(Action.scala:464) at play.api.mvc.ActionBuilder$$anonfun$apply$17.apply(Action.scala:464) at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:433) at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:432) at play.api.mvc.Action$.invokeBlock(Action.scala:556) at play.api.mvc.Action$.invokeBlock(Action.scala:555) at play.api.mvc.ActionBuilder$$anon$1.apply(Action.scala:518) at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130) at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130) at play.utils.Threads$.withContextClassLoader(Threads.scala:21) at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:129) at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:128) at scala.Option.map(Option.scala:146) at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:128) at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:121) at play.api.libs.iteratee.DoneIteratee$$anonfun$mapM$2.apply(Iteratee.scala:705) at play.api.libs.iteratee.DoneIteratee$$anonfun$mapM$2.apply(Iteratee.scala:705) at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41) at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393) at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) Caused by: com.esotericsoftware.kryo.KryoException: Unable to find class: User at com.esotericsoftware.kryo.util.DefaultClassResolver.readName(DefaultClassResolver.java:138) at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:115) at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:610) at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:721) at com.twitter.chill.SerDeState.readClassAndObject(SerDeState.java:61) at com.twitter.chill.KryoPool.fromBytes(KryoPool.java:94) at com.twitter.chill.KryoInjection$$anonfun$invert$1.apply(KryoInjection.scala:30) at com.twitter.chill.KryoInjection$$anonfun$invert$1.apply(KryoInjection.scala:30) at com.twitter.bijection.Inversion$$anonfun$attempt$1.apply(Inversion.scala:30) at scala.util.Try$.apply(Try.scala:192) ... 36 more Caused by: java.lang.ClassNotFoundException: User at java.net.URLClassLoader.findClass(URLClassLoader.java:381) at java.lang.ClassLoader.loadClass(ClassLoader.java:424) at java.lang.ClassLoader.loadClass(ClassLoader.java:357) at java.lang.Class.forName0(Native Method) at java.lang.Class.forName(Class.java:348) at com.esotericsoftware.kryo.util.DefaultClassResolver.readName(DefaultClassResolver.java:136) ... 45 more 17:24:48.942 276700 [play-akka.actor.default-dispatcher-7] UserSerializer ERROR - deserializer from Client : ()

**Comment by johnynek** [comment]
well, you have a ClassNotFound. Is this User class in the jar/classpath of your client?

**Comment by ianoc** [comment]
No response from reporter in a long time. presuming they are good now. Killing.
