### ISSUE TITLE
publish 0.7.5 and 0.8.1 with ArraySerializer fix

### ISSUE THREAD

**Issue by johnynek** [twitter/chill#262]
#257 should be ported to the 0.7.x branch (kryo 2.x) which is still required by people who can't change their kryo implementation.

Then we should publish a new version.

/cc @isnotinvain I'm on PTO next week. Can someone at Twitter publish a point release?

**Comment by johnynek** [comment]
@chermenin

**Comment by chermenin** [comment]
Well, what's going with it?

**Comment by johnynek** [comment]
@chermenin https://github.com/twitter/chill/releases/tag/v0.8.1 that is published. 0.7.5 still has to have some merges.
