### ISSUE TITLE
Add Scala 2.12 support

### ISSUE THREAD

**Issue by LukaszByczynski** [twitter/chill#266]
The title says it all

**Comment by jodersky** [comment]
this is happening in #253

**Comment by ritschwumm** [comment]
which is merged now - how about a release?

**Comment by ritschwumm** [comment]
pretty please?

**Comment by sritchie** [comment]
@ritschwumm, @johnynek and I are going to take care of this on Monday. We cleaned up the build a bit with #271 - we'll release algebird first so we can get 2.12 support for chill-algebird as well. Thanks for the push!

**Comment by fkowal** [comment]
any luck?

**Comment by ritschwumm** [comment]
well, he didn't say _which_ monday ;)

**Comment by johnynek** [comment]
okay... I'll work on this now.

It's quite complex because we have three branches 0.7, 0.8, and 0.9 each with different Kryos. We need to release for each version on each of those branches.

**Comment by johnynek** [comment]
https://github.com/twitter/chill/releases/tag/v0.9.0

There is 0.9.0 with Kryo 4.0.0. Next is 0.8.2 with Scala 2.12.

**Comment by fkowal** [comment]
maven might still be indexing
but http://search.maven.org/#search%7Cga%7C1%7Cchill-akka
i can't seem to find any chill-akka_2.12 artifacts

**Comment by johnynek** [comment]
https://github.com/twitter/chill/pull/272

here is the 0.8 branch.

**Comment by johnynek** [comment]
@fkowal looks like akka was explicitly excluded: https://github.com/twitter/chill/pull/272/files#diff-fdc3abdfd754eeb24090dbd90aeec2ceR156 maybe akka was not on 2.12 when the PR was made?

**Comment by fkowal** [comment]
sure looks like it, 2.12 support in akka starts from version 2.4.12

**Comment by johnynek** [comment]
can you make a PR to fix the build for akka? I don't use and have never used akka in production, so I don't really know what the story is.

Generally, we want the lowest version available that will cover the most commonly used versions in production.

Akka should probably be a provided dependency, and the person using chill-akka should set the version they need (so we just need to have some version that has the same basic API for the parts we use).

**Comment by sritchie-stripe** [comment]
I actually did this a few weeks ago:

https://github.com/twitter/chill/tree/sritchie/akka_upgrades

@fkowal, would you mind taking the fixes from that branch and sending a new PR with the version of Akka that you prefer?

**Comment by fkowal** [comment]
on it

**Comment by fkowal** [comment]
PR ready https://github.com/twitter/chill/pull/273 that should do it

**Comment by fkowal** [comment]
PR ready, tests are passing

**Comment by fkowal** [comment]
i cherrypicked the changes to branches 0.7 and 0.8 and made pull requests
Can you publish the chill-akka_2.12 artifacts after?

**Comment by johnynek** [comment]
Yes, I'll publish all three branches tomorrow. Thanks for your help!

**Comment by fkowal** [comment]
looking forward for chill-akka_2.12 artifacts :)

**Comment by johnynek** [comment]
sorry, I didn't have time to get to it. I'll republish today.

**Comment by johnynek** [comment]
https://github.com/twitter/chill/releases/tag/v0.9.1

**Comment by johnynek** [comment]
https://github.com/twitter/chill/releases/tag/v0.7.5

**Comment by johnynek** [comment]
https://github.com/twitter/chill/releases/tag/v0.8.2

**Comment by johnynek** [comment]
should be done.

We need to fix scrooge for 2.12 and algebird.

**Comment by fkowal** [comment]
0.9.1 looks ok, but 0.8.2 and 0.7.5 is missing chill-java artifacts in maven

**Comment by johnynek** [comment]
well that sucks, but for the mean time, any non-scala part (like
chill-java) has not really changed, so you can use the previous version.

I guess the publishing failed. Are you actually blocked?

**Comment by johnynek** [comment]
@fkowal I guess related to #277 the publish failed and I didn't notice.

**Comment by fkowal** [comment]
I am good with 0.9.1. I hope u can republish a single artifact

**Comment by johnynek** [comment]
okay, 0.8.3 (Kryo 3.0) https://github.com/twitter/chill/releases/tag/v0.8.3 and 0.7.6 (Kryo 2.21) https://github.com/twitter/chill/tree/v0.7.6
