### ISSUE TITLE
Scala 2.11.x java.lang.ClassNotFoundException: scala.Function0

### ISSUE THREAD

**Issue by l15k4** [twitter/chill#283]
Hey,

this snippet https://gist.github.com/l15k4/c0fc99e8b4c51002b6c263885a67b809 runs fine on scala 2.12.x but it throws : 
```
 java.lang.ClassNotFoundException: scala.Function0
```
If I change to 2.11.x version. Any idea what is going on ?

**Comment by ulyssepence** [comment]
@l15k4 sounds like the scala standard library is missing from the runtime. How are you running it?

**Comment by l15k4** [comment]
@benpence hey, it can be reproduced by adding : 
```
"com.twitter"             %% "chill"                  % "0.9.1"
```
to https://github.com/l15k4/scala-collections-benchmark and  : 
```
>;clean;runMain TwitterChillPlayGround
```
Works with `2.12.x`, throws exception with `2.11.x` ... I know it's strange, I'll try that out eventually in other projects too.

**Comment by ulyssepence** [comment]
Hmm, I'm not familiar with `TwitterChillPlayGround`. Is this just a direct `java` invocation?

**Comment by l15k4** [comment]
That's the `object TwitterChillPlayGround extends App` from the gist above. If you added the `object` from gist to the scala-collections-benchmark project and run it, you would get the the exception with 2.11.x and not with 2.12.x

**Comment by johnynek** [comment]
Note we have tests almost exactly like this. That suggests to me something
is wrong with your build or cached artifacts.

**Comment by l15k4** [comment]
You're right, it was a corrupted jar file, it works now after deleting the cache files . Thanks !

**Comment by johnynek** [comment]
Wouldn't it be nice if sbt kept hashes of files it put in the cache or it
actually checked the publish hash files on the maven servers?
