### ISSUE TITLE
Purpose of SerDeState Output backed by ByteArrayOutputStream?

### ISSUE THREAD

**Issue by jcdavis** [twitter/chill#289]
Currently, `KryoSerialization` gets its `KryoPool` by calling `withByteArrayOutputStream`, which returns a `SerDeState` whose `Output` has a `ByteArrayOutputStream`. I've been poking around this code trying to figure out what the purpose of the stream is, without luck. So, my confusion:

Creating an `Output` backed by a stream means that instead of resizing the buffer in `require` it just flushes to the stream. But since the `ByteArrayOutputStream` itself is just a resizing byte array, what is the advantage of having the stream? There is still a single big array, whose reference is kept around (which is probably a good thing in this case), it just lives in the stream instead of the output.

If we removed the stream in favor of just `new Output(4096, -1)` (Same initial size, no maximum), then the `Output` itself would handle the array resizing. Then, inside `writeOutputTo`, calling `out.write(output.getBuffer(), 0, output.position())` would write out the serialized bytes with a single copy, whereas currently there are 2 (from the Output buffer to the `ByteArrayOutputStream` in 1 or more calls to `flush`, plus then again from that stream to the `OutputStream`)

(This double-copy concern is also true of the Standard `SerDeState.writeOutputTo`, but changing that seems less scary)

Am I see things correctly here? This is a little wierd as an issue, but I figured I would try to figure out if I'm understanding things properly before I opened a PR.

**Comment by johnynek** [comment]
The original reason for this repo was for hadoop serialization in scalding. So we had to conform to the hadoop serialization API, which expects you to write into an OutputStream:

https://github.com/twitter/chill/blob/develop/chill-hadoop/src/main/java/com/twitter/chill/hadoop/KryoSerializer.java#L51

Note, you don't have to use `KryoPool.withByteArrayOutputStream`, but you can. You can just call `KryoPool.withBuffer` and get the behavior you want.

But at the time (I believe) there was no efficient way to write from an Output into a Stream without the copy, so we used this approach.

Yes, the buffer issue you mention is real: it will grow without shrinking, but again, we use that method in hadoop where you are generally dealing with similarly sized records and you are going to run for a finite period of time.

**Comment by jcdavis** [comment]
I'm certainly not familiar with the history, but you can efficiently write a Kryo `Output` to a stream  via the `out.write(output.getBuffer(), 0, output.position())` I mentioned above (`getBuffer` returns the full array, which is filled from 0 until `position`). Both the normal SerDeState `KryoPool.withBuffer` as well as `KryoPool.withByteArrayOutputStream` do the double copy (albeit in different ways), though I would be happy to try and remedy that :)

**Comment by jcdavis** [comment]
I added a quick fix for the 2nd case in #290 .
