### ISSUE TITLE
Automatically select Java or Scala？

### ISSUE THREAD

**Issue by GeTOUO** [twitter/chill#431]
In my project, when serializing, I don't know whether Java or Scala instances are passed in. How can I be compatible with both type

**Comment by johnynek** [comment]
I don't think I know what you mean here. Java and scala instances are both just JVM classes, so it shouldn't matter with chill/kryo.

Are you talking about serializing a scala List but getting a java list back out? that's not going to work. I would instead use the scala collection interop code: https://docs.scala-lang.org/overviews/collections/conversions-between-java-and-scala-collections.html

**Comment by GeTOUO** [comment]
thank. This library works very well and meets my expectations. I was looking for a library that is fully Java and scala compatible when serializing and deserializing. I just tried chill. Completely working!
